const commitData = {
    branch: {
        name: 'Feature Branch',
        commits: [
            { id: 'a', parents: ['b'], author: 'Alice', date: '2025-07-05', message: 'feat: Initial commit' },
            { id: 'b', parents: ['c'], author: 'Bob', date: '2025-07-04', message: 'feat: Add README' },
            { id: 'd', parents: ['c'], author: 'Alice', date: '2025-07-04', message: 'feat: Add feature X' },
            { id: 'c', parents: [], author: 'Charlie', date: '2025-07-03', message: 'Initial commit' },
        ],
    },
    trunk: {
        name: 'Main Trunk',
        commits: [
            { id: 'a', parents: ['b', 'd'], author: 'Alice', date: '2025-07-05', message: 'merge: Merge feature branch' },
            { id: 'b', parents: ['c'], author: 'Bob', date: '2025-07-04', message: 'fix: Update main branch' },
            { id: 'd', parents: ['e'], author: 'Charlie', date: '2025-07-04', message: 'feat: Implement feature Y' },
            { id: 'e', parents: ['c'], author: 'Charlie', date: '2025-07-03', message: 'feat: Start feature Y' },
            { id: 'c', parents: ['f'], author: 'Bob', date: '2025-07-02', message: 'refactor: Tweak styles' },
            { id: 'f', parents: [], author: 'Alice', date: '2025-07-01', message: 'Initial commit' },
        ],
    },
    complex: {
        name: 'Complex History',
        commits: [
            { id: 'a', parents: ['b', 'c'], author: 'Alice', date: '2025-07-10', message: 'merge: Merge release branch' },
            { id: 'b', parents: ['d'], author: 'Bob', date: '2025-07-09', message: 'fix: Hotfix on main' },
            { id: 'c', parents: ['e', 'f'], author: 'Charlie', date: '2025-07-08', message: 'merge: Merge feature Z into release' },
            { id: 'd', parents: ['g'], author: 'Bob', date: '2025-07-07', message: 'feat: Main branch development' },
            { id: 'e', parents: ['h'], author: 'Dana', date: '2025-07-06', message: 'feat: Implement feature Z' },
            { id: 'f', parents: ['h'], author: 'Eve', date: '2025-07-05', message: 'feat: Implement feature W' },
            { id: 'h', parents: ['g'], author: 'Charlie', date: '2025-07-04', message: 'chore: Start release branch' },
            { id: 'g', parents: ['i'], author: 'Bob', date: '2025-07-03', message: 'refactor: Core logic' },
            { id: 'i', parents: [], author: 'Alice', date: '2025-07-01', message: 'Initial commit' },
        ],
    },
    non_planar: {
        name: 'Non-Planar Graph',
        commits: [
            { id: 'a', parents: ['b', 'c'], message: 'Merge feature-A and feature-B', author: 'Alice', date: '2025-07-20' },
            { id: 'b', parents: ['d', 'e'], message: 'Merge sub-feature-A1 into feature-A', author: 'Bob', date: '2025-07-19' },
            { id: 'c', parents: ['f', 'g'], message: 'Merge sub-feature-B1 into feature-B', author: 'Charlie', date: '2025-07-18' },
            { id: 'd', parents: ['h'], message: 'Develop feature-A', author: 'Dana', date: '2025-07-17' },
            { id: 'e', parents: ['i'], message: 'Develop sub-feature-A1', author: 'Eve', date: '2025-07-16' },
            { id: 'f', parents: ['j'], message: 'Develop feature-B', author: 'Frank', date: '2025-07-15' },
            { id: 'g', parents: ['k'], message: 'Develop sub-feature-B1', author: 'Grace', date: '2025-07-14' },
            { id: 'h', parents: ['l'], message: 'Branch for feature-A', author: 'Heidi', date: '2025-07-13' },
            { id: 'i', parents: ['l'], message: 'Branch for sub-feature-A1', author: 'Ivan', date: '2025-07-12' },
            { id: 'j', parents: ['m'], message: 'Branch for feature-B', author: 'Judy', date: '2025-07-11' },
            { id: 'k', parents: ['m'], message: 'Branch for sub-feature-B1', author: 'Mallory', date: '2025-07-10' },
            { id: 'l', parents: ['n'], message: 'Develop on main', author: 'Niaj', date: '2025-07-09' },
            { id: 'm', parents: ['n'], message: 'Another development on main', author: 'Olivia', date: '2025-07-08' },
            { id: 'n', parents: [], message: 'Initial commit', author: 'Peggy', date: '2025-07-07' },
        ],
    },
    octopus: {
        name: 'Octopus Merge',
        commits: [
            { id: 'a', parents: ['b', 'c', 'd', 'e'], message: 'Octopus merge of multiple branches', author: 'Alice', date: '2025-07-25' },
            { id: 'b', parents: ['f'], message: 'Feature branch 1', author: 'Bob', date: '2025-07-24' },
            { id: 'c', parents: ['g'], message: 'Feature branch 2', author: 'Charlie', date: '2025-07-23' },
            { id: 'd', parents: ['h'], message: 'Feature branch 3', author: 'Dana', date: '2025-07-22' },
            { id: 'e', parents: ['i'], message: 'Feature branch 4', author: 'Eve', date: '2025-07-21' },
            { id: 'f', parents: [], message: 'Initial commit for branch 1', author: 'Frank', date: '2025-07-20' },
            { id: 'g', parents: [], message: 'Initial commit for branch 2', author: 'Grace', date: '2025-07-19' },
            { id: 'h', parents: [], message: 'Initial commit for branch 3', author: 'Heidi', date: '2025-07-18' },
            { id: 'i', parents: [], message: 'Initial commit for branch 4', author: 'Ivan', date: '2025-07-17' },
        ],
    },
    sharedParents: {
        name: 'Shared Parents',
        commits: [
            { id: 'a', parents: ['b', 'c'], message: 'Child 1 from shared parents', author: 'Alice', date: '2025-07-30' },
            { id: 'd', parents: ['b', 'c'], message: 'Child 2 from shared parents', author: 'Bob', date: '2025-07-29' },
            { id: 'b', parents: ['e'], message: 'Parent 1', author: 'Charlie', date: '2025-07-28' },
            { id: 'c', parents: ['e'], message: 'Parent 2', author: 'Dana', date: '2025-07-27' },
            { id: 'e', parents: [], message: 'Initial commit for shared parents', author: 'Eve', date: '2025-07-26' },
        ],
    },
    disconnected: {
        name: 'Disconnected Graph',
        commits: [
            { id: 'a', parents: [], message: 'Standalone commit', author: 'Alice', date: '2025-08-01' },
            { id: 'b', parents: [], message: 'Another standalone commit', author: 'Bob', date: '2025-08-02' },
        ],
    },
    circular: {
        name: 'Circular Reference',
        commits: [
            { id: 'a', parents: ['b'], message: 'Circular commit A', author: 'Alice', date: '2025-08-03' },
            { id: 'b', parents: ['a'], message: 'Circular commit B', author: 'Bob', date: '2025-08-04' },
        ],
    },
    deepBranching: {
        name: 'Deep Branching',
        commits: [
            { id: 'F1', parents: ['E1'], message: 'Branch F1 from E1', author: 'Mallory', date: '2025-08-15' },
            { id: 'E2', parents: ['E1'], message: 'Branch E2 from E1', author: 'Judy', date: '2025-08-14' },
            { id: 'E1', parents: ['D1'], message: 'Branch E1 from D1', author: 'Ivan', date: '2025-08-13' },
            { id: 'D2', parents: ['D1'], message: 'Branch D2 from D1', author: 'Heidi', date: '2025-08-12' },
            { id: 'D1', parents: ['C1'], message: 'Branch D1 from C1', author: 'Grace', date: '2025-08-11' },
            { id: 'C2', parents: ['C1'], message: 'Branch C2 from C1', author: 'Frank', date: '2025-08-10' },
            { id: 'C1', parents: ['B1'], message: 'Branch C1 from B1', author: 'Eve', date: '2025-08-09' },
            { id: 'B2', parents: ['B1'], message: 'Branch B2 from B1', author: 'Dana', date: '2025-08-08' },
            { id: 'B1', parents: ['A1'], message: 'Branch B1 from A1', author: 'Charlie', date: '2025-08-07' },
            { id: 'A2', parents: ['A1'], message: 'Branch A2 from A1', author: 'Bob', date: '2025-08-06' },
            { id: 'A1', parents: [], message: 'Root commit', author: 'Alice', date: '2025-08-05' },
        ],
    },
};
